Updated VS 2008 Documentation & Gitignore for VS builds
HydraIRC/hydrairc pull request #19
Opened 2022-04-07 05:13 UTC by gdwnldsKSC

I've created a gitignore that ignores the artifacts created by visual studio that aren't relevant to source control (user-local configs, autogenerated intellisense database, etc), as well as updated the documentation with explicit steps required to compile under VS 2008.

2022-09-23 07:36 UTC, gdwnldsKSC commented
Updated with libxml version updates and GPL notification changes in about dialog

2022-09-23 12:44 UTC, hydra commented on HydraIRC/version.h
> +#define AUTHORSTRING "Dominic Clifton aka Hydra\n Upgrades and newer OS and VS support by gdwnldsKSC"
Understand you'd like some attribute, but not via this.  Feel free to add additional strings and make them appear on the Help/About dialog.

2022-09-23 12:46 UTC, hydra requested changes
Can you also remove the `.map` file and add it to `.gitignore`?

All good except for the above and the `AUTHORSTRING` change.  I note that you've already updated the aboutdlg.cpp file, that should be fine right?

2022-09-25 04:48 UTC, gdwnldsKSC commented
@hydra Should be good now, made the requested AUTHORSTRING change and updated gitignore to remove map and pdb files from the distro folders. 

Been quite the adventure so far trying to drag this thing kicking and screaming into the future. Lots more to do, but it's shaping up to be a fun challenge.

2022-09-25 08:02 UTC, merged

2022-09-25 08:03 UTC, hydra commented
Merged, thanks!